GET {{server}}/health


###
GET {{server}}/api/dines


###
GET {{server}}/api/dines/1


###
POST {{server}}/api/dines
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "name": "Test Dine2",
  "price": 1.99,
  "description": "Test text"
}


###
PUT {{server}}/api/dines
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "id": 3,
  "name": "Margherita Pizza",
  "price": 15.99,
  "description": "A classic pizza with fresh mozzarella, tomatoes, and basil on a thin and crispy crust."
}


###
DELETE {{server}}/api/dines/1
Authorization: BEARER {{authToken}}


###
POST {{server}}/api/users/signup
Content-Type: application/json

{
  "name": "John Wayne",
  "email": "john@wayne.com",
  "password": "john@wayne"
}


###
# @name login
POST {{server}}/api/users/login
Content-Type: application/json

{
  "email": "john@wayne.com",
  "password": "john@wayne"
}


###
@authToken = {{login.response.body.token}}

@server = http://localhost:5000
#@server = http://172.16.6.90:5000